# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .acme_certificate import *
from .acme_registration import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_acme.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_acme.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "acme",
  "mod": "index/acmeCertificate",
  "fqn": "pulumi_acme",
  "classes": {
   "acme:index/acmeCertificate:AcmeCertificate": "AcmeCertificate"
  }
 },
 {
  "pkg": "acme",
  "mod": "index/acmeRegistration",
  "fqn": "pulumi_acme",
  "classes": {
   "acme:index/acmeRegistration:AcmeRegistration": "AcmeRegistration"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "acme",
  "token": "pulumi:providers:acme",
  "fqn": "pulumi_acme",
  "class": "Provider"
 }
]
"""
)
