// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface AcmeCertificateDnsChallenge {
    config?: {[key: string]: any};
    provider: string;
}

export interface AcmeCertificateHttpChallenge {
    port?: number;
    proxyHeader?: string;
}

export interface AcmeCertificateHttpMemcachedChallenge {
    hosts: string[];
}

export interface AcmeCertificateHttpWebrootChallenge {
    directory: string;
}

export interface AcmeCertificateTlsChallenge {
    port?: number;
}

export interface AcmeRegistrationExternalAccountBinding {
    hmacBase64: string;
    keyId: string;
}

