// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class AcmeRegistration extends pulumi.CustomResource {
    /**
     * Get an existing AcmeRegistration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AcmeRegistrationState, opts?: pulumi.CustomResourceOptions): AcmeRegistration {
        return new AcmeRegistration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'acme:index/acmeRegistration:AcmeRegistration';

    /**
     * Returns true if the given object is an instance of AcmeRegistration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AcmeRegistration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AcmeRegistration.__pulumiType;
    }

    public readonly accountKeyPem!: pulumi.Output<string>;
    public readonly emailAddress!: pulumi.Output<string>;
    public readonly externalAccountBinding!: pulumi.Output<outputs.AcmeRegistrationExternalAccountBinding | undefined>;
    public /*out*/ readonly registrationUrl!: pulumi.Output<string>;

    /**
     * Create a AcmeRegistration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AcmeRegistrationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AcmeRegistrationArgs | AcmeRegistrationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AcmeRegistrationState | undefined;
            resourceInputs["accountKeyPem"] = state ? state.accountKeyPem : undefined;
            resourceInputs["emailAddress"] = state ? state.emailAddress : undefined;
            resourceInputs["externalAccountBinding"] = state ? state.externalAccountBinding : undefined;
            resourceInputs["registrationUrl"] = state ? state.registrationUrl : undefined;
        } else {
            const args = argsOrState as AcmeRegistrationArgs | undefined;
            if ((!args || args.accountKeyPem === undefined) && !opts.urn) {
                throw new Error("Missing required property 'accountKeyPem'");
            }
            if ((!args || args.emailAddress === undefined) && !opts.urn) {
                throw new Error("Missing required property 'emailAddress'");
            }
            resourceInputs["accountKeyPem"] = args ? args.accountKeyPem : undefined;
            resourceInputs["emailAddress"] = args ? args.emailAddress : undefined;
            resourceInputs["externalAccountBinding"] = args ? args.externalAccountBinding : undefined;
            resourceInputs["registrationUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AcmeRegistration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AcmeRegistration resources.
 */
export interface AcmeRegistrationState {
    accountKeyPem?: pulumi.Input<string>;
    emailAddress?: pulumi.Input<string>;
    externalAccountBinding?: pulumi.Input<inputs.AcmeRegistrationExternalAccountBinding>;
    registrationUrl?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AcmeRegistration resource.
 */
export interface AcmeRegistrationArgs {
    accountKeyPem: pulumi.Input<string>;
    emailAddress: pulumi.Input<string>;
    externalAccountBinding?: pulumi.Input<inputs.AcmeRegistrationExternalAccountBinding>;
}
